"""
Integration tests — repository CRUD, transactions, rollback, and relationships.

These tests verify the actual SQL generated by repositories against a live
PostgreSQL database. They complement the unit tests (which use mock sessions)
by testing:
  - Real INSERT / SELECT / UPDATE / DELETE behaviour
  - Unique constraint enforcement (slug collision)
  - FK constraint enforcement (invalid org_id)
  - Transaction rollback isolation
  - Cursor pagination with real data
  - Relationship loading with selectinload()
  - soft-delete visibility rules

Skipped when DATABASE_URL is not set.
"""
from __future__ import annotations

import uuid

import pytest
import pytest_asyncio
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.db.mixins import uuid7
from app.models.membership import Membership, MembershipRole
from app.models.organization import Organization, OrganizationStatus
from app.models.project import Project, ProjectEnvironment
from app.models.provider_connection import ProviderConnection, ProviderType
from app.repositories.membership_repository import MembershipRepository
from app.repositories.organization_repository import OrganizationRepository
from app.repositories.project_repository import ProjectRepository
from app.repositories.provider_connection_repository import ProviderConnectionRepository
from tests.conftest import make_connection, make_membership, make_org, make_project
from tests.integration.conftest import requires_db


# ── Helpers ───────────────────────────────────────────────────────────────────


async def _persist_org(session: AsyncSession, **kwargs: object) -> Organization:
    repo = OrganizationRepository(session)
    org = make_org(**kwargs)  # type: ignore[arg-type]
    await repo.create(org)
    return org


# ── Organization CRUD ─────────────────────────────────────────────────────────


@requires_db
@pytest.mark.integration
class TestOrganizationRepositoryIntegration:
    async def test_create_and_retrieve(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="acme-integration")
        repo = OrganizationRepository(db_session)

        found = await repo.get(org.id)
        assert found is not None
        assert found.slug == "acme-integration"

    async def test_get_by_slug(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        await _persist_org(db_session, slug="find-by-slug")
        repo = OrganizationRepository(db_session)
        found = await repo.get_by_slug("find-by-slug")
        assert found is not None
        assert found.name == "Acme Corp"

    async def test_slug_exists_true(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        await _persist_org(db_session, slug="taken-slug")
        repo = OrganizationRepository(db_session)
        assert await repo.slug_exists("taken-slug") is True

    async def test_slug_exists_false(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        repo = OrganizationRepository(db_session)
        assert await repo.slug_exists("this-slug-does-not-exist-xyz") is False

    async def test_slug_exists_excludes_own_id(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="update-slug")
        repo = OrganizationRepository(db_session)
        # Excluding its own id: should return False (no OTHER org has the slug)
        exists = await repo.slug_exists("update-slug", exclude_id=org.id)
        assert exists is False

    async def test_soft_delete_makes_record_invisible(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="to-soft-delete")
        repo = OrganizationRepository(db_session)

        await repo.soft_delete(org)

        # get() filters deleted_at IS NULL — should return None
        found = await repo.get(org.id)
        assert found is None
        # slug_exists() also filters active only — should return False
        assert await repo.slug_exists("to-soft-delete") is False

    async def test_list_by_status(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        await _persist_org(db_session, slug="active-1", status=OrganizationStatus.ACTIVE)
        await _persist_org(db_session, slug="suspended-1", status=OrganizationStatus.SUSPENDED)
        repo = OrganizationRepository(db_session)

        page = await repo.list_by_status(OrganizationStatus.ACTIVE)
        slugs = [o.slug for o in page.items]
        assert "active-1" in slugs
        assert "suspended-1" not in slugs

    async def test_cursor_pagination(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        for i in range(5):
            await _persist_org(db_session, slug=f"paginated-{i}")

        repo = OrganizationRepository(db_session)
        page1 = await repo.list_page(limit=3)
        assert len(page1.items) <= 3

        if page1.has_more and page1.next_cursor:
            page2 = await repo.list_page(limit=3, cursor=page1.next_cursor)
            # No overlap between pages
            ids1 = {o.id for o in page1.items}
            ids2 = {o.id for o in page2.items}
            assert ids1.isdisjoint(ids2)


# ── Transaction and rollback ──────────────────────────────────────────────────


@requires_db
@pytest.mark.integration
class TestTransactionIsolation:
    async def test_rollback_discards_changes(
        self, integration_engine: AsyncEngine, run_migrations: str  # type: ignore[name-defined]
    ) -> None:
        """
        Changes made inside a rolled-back transaction must not be visible
        to subsequent transactions.
        """
        from sqlalchemy.ext.asyncio import async_sessionmaker

        factory = async_sessionmaker(
            integration_engine, expire_on_commit=False, autoflush=False
        )

        slug = f"rollback-test-{uuid.uuid4().hex[:8]}"

        # Write in one session, then roll it back
        async with factory() as s1:
            async with s1.begin():
                org = make_org(slug=slug)
                s1.add(org)
                await s1.flush()
                await s1.rollback()

        # Verify it's not visible in a fresh session
        async with factory() as s2:
            async with s2.begin():
                result = await s2.execute(
                    select(Organization).where(Organization.slug == slug)
                )
                assert result.scalar_one_or_none() is None


# ── Relationship loading ──────────────────────────────────────────────────────


@requires_db
@pytest.mark.integration
class TestRelationshipLoading:
    async def test_accessing_unloaded_relationship_raises(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        """
        lazy="raise" means accessing a relationship without selectinload()
        must raise InvalidRequestError, not silently execute SQL.
        """
        from sqlalchemy.exc import InvalidRequestError

        org = await _persist_org(db_session, slug="lazy-raise-test")

        # Reload from DB without eager loading
        fresh_org = await OrganizationRepository(db_session).get(org.id)
        assert fresh_org is not None

        with pytest.raises(InvalidRequestError):
            _ = fresh_org.projects  # type: ignore[attr-defined]  # must raise

    async def test_selectinload_loads_relationship(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        """selectinload() must make the relationship accessible without error."""
        org = await _persist_org(db_session, slug="selectinload-test")
        proj_repo = ProjectRepository(db_session)
        proj = make_project(org_id=org.id, name="Test Project")
        await proj_repo.create(proj)

        # Reload with explicit eager loading
        stmt = (
            select(Organization)
            .where(Organization.id == org.id)
            .options(selectinload(Organization.projects))
        )
        result = await db_session.execute(stmt)
        loaded_org = result.scalar_one()

        assert len(loaded_org.projects) == 1
        assert loaded_org.projects[0].name == "Test Project"


# ── Project Repository ────────────────────────────────────────────────────────


@requires_db
@pytest.mark.integration
class TestProjectRepositoryIntegration:
    async def test_create_and_list_by_org(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="proj-org")
        proj_repo = ProjectRepository(db_session)

        proj1 = make_project(org_id=org.id, name="Alpha")
        proj2 = make_project(org_id=org.id, name="Beta", environment=ProjectEnvironment.STAGING)
        await proj_repo.create(proj1)
        await proj_repo.create(proj2)

        page = await proj_repo.list_by_org(org.id)
        names = [p.name for p in page.items]
        assert "Alpha" in names
        assert "Beta" in names

    async def test_list_by_org_and_env(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="env-filter-org")
        proj_repo = ProjectRepository(db_session)

        await proj_repo.create(make_project(org_id=org.id, name="Prod", environment=ProjectEnvironment.PRODUCTION))
        await proj_repo.create(make_project(org_id=org.id, name="Dev", environment=ProjectEnvironment.DEVELOPMENT))

        page = await proj_repo.list_by_org_and_env(org.id, ProjectEnvironment.PRODUCTION)
        assert all(p.environment == ProjectEnvironment.PRODUCTION for p in page.items)

    async def test_count_by_org(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="count-org")
        proj_repo = ProjectRepository(db_session)

        await proj_repo.create(make_project(org_id=org.id, name="P1"))
        await proj_repo.create(make_project(org_id=org.id, name="P2"))

        count = await proj_repo.count_by_org(org.id)
        assert count == 2


# ── Membership Repository ─────────────────────────────────────────────────────


@requires_db
@pytest.mark.integration
class TestMembershipRepositoryIntegration:
    async def test_create_and_get_by_email(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="mem-org")
        repo = MembershipRepository(db_session)
        mem = make_membership(org_id=org.id, user_email="bob@example.com", role=MembershipRole.ADMIN)
        await repo.create(mem)

        found = await repo.get_by_org_and_email(org.id, "bob@example.com")
        assert found is not None
        assert found.role == MembershipRole.ADMIN

    async def test_list_by_email_across_orgs(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org1 = await _persist_org(db_session, slug="multi-org-1")
        org2 = await _persist_org(db_session, slug="multi-org-2")
        repo = MembershipRepository(db_session)

        await repo.create(make_membership(org_id=org1.id, user_email="shared@example.com"))
        await repo.create(make_membership(org_id=org2.id, user_email="shared@example.com"))

        page = await repo.list_by_email("shared@example.com")
        assert len(page.items) == 2

    async def test_list_by_org_and_role(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="role-filter-org")
        repo = MembershipRepository(db_session)

        await repo.create(make_membership(org_id=org.id, user_email="owner@e.com", role=MembershipRole.OWNER))
        await repo.create(make_membership(org_id=org.id, user_email="viewer@e.com", role=MembershipRole.VIEWER))

        page = await repo.list_by_org_and_role(org.id, MembershipRole.OWNER)
        assert all(m.role == MembershipRole.OWNER for m in page.items)
        assert len(page.items) == 1


# ── ProviderConnection Repository ─────────────────────────────────────────────


@requires_db
@pytest.mark.integration
class TestProviderConnectionRepositoryIntegration:
    async def test_create_and_list_active_by_org(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="conn-org")
        repo = ProviderConnectionRepository(db_session)

        conn_active = make_connection(org_id=org.id, provider_type=ProviderType.OPENAI)
        conn_inactive = make_connection(org_id=org.id, provider_type=ProviderType.ANTHROPIC)
        conn_inactive.is_active = False

        await repo.create(conn_active)
        await repo.create(conn_inactive)

        page = await repo.list_active_by_org(org.id)
        assert all(c.is_active for c in page.items)
        active_types = [c.provider_type for c in page.items]
        assert ProviderType.OPENAI in active_types
        assert ProviderType.ANTHROPIC not in active_types

    async def test_list_by_type(
        self, db_session: AsyncSession, run_migrations: str
    ) -> None:
        org = await _persist_org(db_session, slug="type-filter-org")
        repo = ProviderConnectionRepository(db_session)

        await repo.create(make_connection(org_id=org.id, provider_type=ProviderType.OPENAI))
        await repo.create(make_connection(org_id=org.id, provider_type=ProviderType.ANTHROPIC))

        page = await repo.list_by_type(org.id, ProviderType.OPENAI)
        assert all(c.provider_type == ProviderType.OPENAI for c in page.items)
